#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Optimized Figure 2
==================

A. Eight model-specific 3x3 mean CKA matrices
   - diagonal explicitly shown as 1.000

B. Model-wise cross-scale CKA profile
   - three scale-pair values
   - black diamond = mean off-diagonal CKA

C. Patch-sampling sensitivity
   - full-patch vs 1024-patch CKA
   - color encodes scale pair only
   - identity line
   - max |ΔCKA| and Spearman rho

Input:
    outputs generated by
    25_figure2_cka_sampling_sensitivity_8pfm.py

No CKA recomputation.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import spearmanr


# ============================================================
# PATHS
# ============================================================

SCRIPT = Path(__file__).resolve()
NATIVE_ROOT = SCRIPT.parents[1]

RESULT_ROOT = (
    NATIVE_ROOT
    / "reviewer_analysis"
    / "results"
)

FIG_ROOT = (
    NATIVE_ROOT
    / "reviewer_analysis"
    / "figures"
)

FIG_ROOT.mkdir(
    parents=True,
    exist_ok=True,
)

PREFIX = "25_figure2_cka_sampling_sensitivity_8pfm"

PAIR_FILE = (
    RESULT_ROOT
    / f"{PREFIX}_panel_data.csv"
)

SENS_FILE = (
    RESULT_ROOT
    / f"{PREFIX}_sampling_sensitivity.csv"
)

OUT_PNG = (
    FIG_ROOT
    / "Figure2_CKA_Optimized_FINAL_8PFM.png"
)

OUT_PDF = (
    FIG_ROOT
    / "Figure2_CKA_Optimized_FINAL_8PFM.pdf"
)

OUT_TIFF = (
    FIG_ROOT
    / "Figure2_CKA_Optimized_FINAL_8PFM_600dpi.tiff"
)


# ============================================================
# CONFIG
# ============================================================

MODELS = [
    "phikon",
    "uni",
    "virchow",
    "virchow2",
    "uni2",
    "midnight",
    "gigapath",
    "gigapath_flash",
]

MODEL_DISPLAY = {
    "phikon": "Phikon",
    "uni": "UNI",
    "virchow": "Virchow",
    "virchow2": "Virchow2",
    "uni2": "UNI2",
    "midnight": "Midnight",
    "gigapath": "GigaPath",
    "gigapath_flash": "GigaPath-Flash",
}

SCALES = [
    "40x",
    "10x",
    "2p5x",
]

SCALE_DISPLAY = {
    "40x": "40×",
    "10x": "10×",
    "2p5x": "2.5×",
}

PAIR_ORDER = [
    ("40x", "10x"),
    ("10x", "2p5x"),
    ("40x", "2p5x"),
]

PAIR_LABEL = {
    ("40x", "10x"): "40×↔10×",
    ("10x", "2p5x"): "10×↔2.5×",
    ("40x", "2p5x"): "40×↔2.5×",
}

# Keep scale-pair encoding consistent between B and C.
PAIR_COLOR = {
    "40×↔10×": "#D55E00",
    "10×↔2.5×": "#0072B2",
    "40×↔2.5×": "#009E73",
}

PAIR_MARKER = {
    "40×↔10×": "o",
    "10×↔2.5×": "s",
    "40×↔2.5×": "^",
}


# ============================================================
# LOAD
# ============================================================

if not PAIR_FILE.exists():
    raise FileNotFoundError(
        f"Missing:\n{PAIR_FILE}\n"
        "Run script 25 first."
    )

if not SENS_FILE.exists():
    raise FileNotFoundError(
        f"Missing:\n{SENS_FILE}\n"
        "Run script 25 first."
    )

pair_df = pd.read_csv(
    PAIR_FILE
)

sens = pd.read_csv(
    SENS_FILE
)


# ============================================================
# AUDIT
# ============================================================

required_pair = {
    "model",
    "pair_a",
    "pair_b",
    "scale_pair",
    "mean_cka",
}

required_sens = {
    "model",
    "scale_pair",
    "cka_full",
    "cka_1024",
}

missing = (
    required_pair
    - set(pair_df.columns)
)

if missing:
    raise RuntimeError(
        f"PAIR_FILE missing columns: {sorted(missing)}"
    )

missing = (
    required_sens
    - set(sens.columns)
)

if missing:
    raise RuntimeError(
        f"SENS_FILE missing columns: {sorted(missing)}"
    )

if len(pair_df) != 24:
    raise RuntimeError(
        f"Expected 24 model×pair rows; found {len(pair_df)}"
    )

if len(sens) != 24:
    raise RuntimeError(
        f"Expected 24 sensitivity points; found {len(sens)}"
    )


# ============================================================
# OVERALL CKA
# ============================================================

overall = (
    pair_df
    .groupby(
        "model",
        as_index=False,
    )
    .agg(
        overall_cka=(
            "mean_cka",
            "mean",
        )
    )
)

overall[
    "model_display"
] = overall[
    "model"
].map(
    MODEL_DISPLAY
)

overall = overall.sort_values(
    "overall_cka",
    ascending=False,
).reset_index(
    drop=True
)

MODEL_RANK_ORDER = overall[
    "model"
].tolist()


# ============================================================
# SENSITIVITY STATS
# ============================================================

sens[
    "abs_delta"
] = np.abs(
    sens[
        "cka_1024"
    ]
    -
    sens[
        "cka_full"
    ]
)

max_delta = float(
    sens[
        "abs_delta"
    ].max()
)

mean_delta = float(
    sens[
        "abs_delta"
    ].mean()
)

rho = float(
    spearmanr(
        sens[
            "cka_full"
        ],
        sens[
            "cka_1024"
        ],
    ).statistic
)


# ============================================================
# STYLE
# ============================================================

plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size": 9.0,
    "axes.titlesize": 10.5,
    "axes.labelsize": 9.5,
    "xtick.labelsize": 8.5,
    "ytick.labelsize": 8.5,
    "legend.fontsize": 8.2,
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
})


# ============================================================
# FIGURE LAYOUT
# ============================================================

fig = plt.figure(
    figsize=(
        13.4,
        9.0,
    ),
)

outer = fig.add_gridspec(
    2,
    1,
    height_ratios=[
        1.62,
        1.0,
    ],
    hspace=0.28,
)


# ============================================================
# PANEL A
# ============================================================

gs_a = outer[
    0
].subgridspec(
    2,
    5,
    width_ratios=[
        1,
        1,
        1,
        1,
        0.07,
    ],
    wspace=0.24,
    hspace=0.37,
)


heat_axes = []
im = None

for i, model in enumerate(
    MODELS
):

    r = i // 4
    c = i % 4

    ax = fig.add_subplot(
        gs_a[
            r,
            c,
        ]
    )

    heat_axes.append(
        ax
    )

    M = np.eye(
        3,
        dtype=float,
    )

    sub = pair_df[
        pair_df[
            "model"
        ]
        == model
    ]

    for _, row in sub.iterrows():

        a = row[
            "pair_a"
        ]

        b = row[
            "pair_b"
        ]

        value = float(
            row[
                "mean_cka"
            ]
        )

        ia = SCALES.index(
            a
        )

        ib = SCALES.index(
            b
        )

        M[
            ia,
            ib
        ] = value

        M[
            ib,
            ia
        ] = value


    im = ax.imshow(
        M,
        vmin=0,
        vmax=1,
        cmap="Purples",
        interpolation="nearest",
        aspect="equal",
    )


    # values
    for rr in range(3):

        for cc in range(3):

            value = M[
                rr,
                cc
            ]

            ax.text(
                cc,
                rr,
                f"{value:.3f}",
                ha="center",
                va="center",
                fontsize=8.6,
                fontweight=(
                    "bold"
                    if rr == cc
                    else "normal"
                ),
                color=(
                    "white"
                    if value >= 0.64
                    else "black"
                ),
            )


    ax.set_title(
        MODEL_DISPLAY[
            model
        ],
        fontweight="bold",
        pad=6,
    )

    ax.set_xticks(
        range(3)
    )

    ax.set_yticks(
        range(3)
    )

    ax.set_xticklabels(
        [
            SCALE_DISPLAY[x]
            for x in SCALES
        ]
    )

    ax.set_yticklabels(
        [
            SCALE_DISPLAY[x]
            for x in SCALES
        ]
    )

    ax.tick_params(
        length=0,
        pad=3,
    )

    for spine in ax.spines.values():
        spine.set_visible(
            False
        )


# Colorbar spans both rows.
cax = fig.add_subplot(
    gs_a[
        :,
        4,
    ]
)

cb = fig.colorbar(
    im,
    cax=cax,
)

cb.set_label(
    "Linear CKA",
    labelpad=7,
)

cb.ax.tick_params(
    labelsize=8,
)


fig.text(
    0.025,
    0.965,
    "A",
    fontsize=16,
    fontweight="bold",
)

fig.text(
    0.050,
    0.965,
    "Cross-scale representation alignment",
    fontsize=12.5,
    fontweight="bold",
)


# ============================================================
# LOWER PANELS
# ============================================================

gs_lower = outer[
    1
].subgridspec(
    1,
    2,
    width_ratios=[
        1.38,
        1.0,
    ],
    wspace=0.30,
)


# ============================================================
# PANEL B
# Horizontal model-wise dot plot
# ============================================================

ax_b = fig.add_subplot(
    gs_lower[
        0,
        0,
    ]
)

y = np.arange(
    len(
        MODEL_RANK_ORDER
    )
)

offset = {
    "40×↔10×": -0.18,
    "10×↔2.5×": 0.00,
    "40×↔2.5×": 0.18,
}


for yi, model in enumerate(
    MODEL_RANK_ORDER
):

    sub = pair_df[
        pair_df[
            "model"
        ]
        == model
    ]

    # faint range connector
    values = sub[
        "mean_cka"
    ].to_numpy(
        dtype=float
    )

    ax_b.hlines(
        yi,
        values.min(),
        values.max(),
        color="0.80",
        linewidth=1.2,
        zorder=1,
    )


    for pair in [
        "40×↔10×",
        "10×↔2.5×",
        "40×↔2.5×",
    ]:

        row = sub[
            sub[
                "scale_pair"
            ]
            == pair
        ]

        value = float(
            row[
                "mean_cka"
            ].iloc[0]
        )

        ax_b.scatter(
            value,
            yi + offset[
                pair
            ],
            s=50,
            marker=PAIR_MARKER[
                pair
            ],
            color=PAIR_COLOR[
                pair
            ],
            edgecolor="white",
            linewidth=0.5,
            zorder=3,
            label=(
                pair
                if yi == 0
                else None
            ),
        )


    overall_value = float(
        overall.loc[
            overall[
                "model"
            ]
            == model,
            "overall_cka",
        ].iloc[0]
    )

    ax_b.scatter(
        overall_value,
        yi,
        s=63,
        marker="D",
        facecolor="black",
        edgecolor="white",
        linewidth=0.7,
        zorder=4,
        label=(
            "Overall mean"
            if yi == 0
            else None
        ),
    )


ax_b.set_yticks(
    y
)

ax_b.set_yticklabels(
    [
        MODEL_DISPLAY[m]
        for m in MODEL_RANK_ORDER
    ]
)

ax_b.invert_yaxis()

ax_b.set_xlim(
    0.25,
    0.86,
)

ax_b.set_xlabel(
    "Mean linear CKA"
)

ax_b.set_title(
    "B   Model-wise cross-scale alignment profiles",
    loc="left",
    fontweight="bold",
)

ax_b.grid(
    axis="x",
    alpha=0.16,
)

ax_b.spines[
    "top"
].set_visible(False)

ax_b.spines[
    "right"
].set_visible(False)

ax_b.spines[
    "left"
].set_visible(False)

ax_b.tick_params(
    axis="y",
    length=0,
)

ax_b.legend(
    frameon=False,
    ncol=2,
    loc="lower right",
    columnspacing=1.2,
    handletextpad=0.5,
)


# ============================================================
# PANEL C
# Sampling sensitivity
# ============================================================

ax_c = fig.add_subplot(
    gs_lower[
        0,
        1,
    ]
)


for pair in [
    "40×↔10×",
    "10×↔2.5×",
    "40×↔2.5×",
]:

    sub = sens[
        sens[
            "scale_pair"
        ]
        == pair
    ]

    ax_c.scatter(
        sub[
            "cka_full"
        ],
        sub[
            "cka_1024"
        ],
        s=54,
        marker=PAIR_MARKER[
            pair
        ],
        color=PAIR_COLOR[
            pair
        ],
        edgecolor="white",
        linewidth=0.6,
        alpha=0.92,
        label=pair,
        zorder=3,
    )


all_values = np.concatenate(
    [
        sens[
            "cka_full"
        ].to_numpy(
            dtype=float
        ),
        sens[
            "cka_1024"
        ].to_numpy(
            dtype=float
        ),
    ]
)

lo = float(
    all_values.min()
) - 0.025

hi = float(
    all_values.max()
) + 0.025


ax_c.plot(
    [
        lo,
        hi,
    ],
    [
        lo,
        hi,
    ],
    linestyle="--",
    linewidth=1.05,
    color="0.45",
    zorder=1,
)

ax_c.set_xlim(
    lo,
    hi,
)

ax_c.set_ylim(
    lo,
    hi,
)

ax_c.set_aspect(
    "equal",
    adjustable="box",
)

ax_c.set_xlabel(
    "Full-patch CKA"
)

ax_c.set_ylabel(
    "1024-patch CKA"
)

ax_c.set_title(
    "C   Patch-sampling sensitivity",
    loc="left",
    fontweight="bold",
)

ax_c.grid(
    alpha=0.14,
)

ax_c.spines[
    "top"
].set_visible(False)

ax_c.spines[
    "right"
].set_visible(False)


annotation = (
    "24 model × scale-pair estimates\n"
    f"max |ΔCKA| = {max_delta:.4f}\n"
    f"Spearman ρ = {rho:.3f}"
)

ax_c.text(
    0.035,
    0.975,
    annotation,
    transform=ax_c.transAxes,
    va="top",
    ha="left",
    fontsize=8.8,
    linespacing=1.15,
)

ax_c.legend(
    frameon=False,
    loc="upper center",
    bbox_to_anchor=(0.5, -0.18),
    ncol=3,
    columnspacing=1.25,
    handletextpad=0.45,
    borderaxespad=0,
    fontsize=8.3,
)


# ============================================================
# FOOTNOTE
# ============================================================

fig.text(
    0.50,
    0.018,
    (
        "Same-scale self-alignment is explicitly shown as 1.000. "
        "Overall CKA is the mean of the three off-diagonal "
        "cross-scale pairs."
    ),
    ha="center",
    fontsize=8.2,
)


fig.subplots_adjust(
    left=0.08,
    right=0.955,
    top=0.925,
    bottom=0.115,
)


# ============================================================
# SAVE
# ============================================================

fig.savefig(
    OUT_PNG,
    dpi=600,
    bbox_inches="tight",
    facecolor="white",
)

fig.savefig(
    OUT_PDF,
    bbox_inches="tight",
    facecolor="white",
)

fig.savefig(
    OUT_TIFF,
    dpi=600,
    bbox_inches="tight",
    facecolor="white",
    pil_kwargs={
        "compression":
            "tiff_lzw",
    },
)

plt.close(
    fig
)


# ============================================================
# REPORT
# ============================================================

print(
    "=" * 100
)

print(
    "FIGURE 2 OPTIMIZED"
)

print(
    "=" * 100
)

print(
    "\nOverall mean CKA ranking:"
)

print(
    overall[
        [
            "model_display",
            "overall_cka",
        ]
    ]
    .round(4)
    .to_string(
        index=False
    )
)

print(
    "\nSampling sensitivity:"
)

print(
    f"max |delta CKA|  = {max_delta:.6f}"
)

print(
    f"mean |delta CKA| = {mean_delta:.6f}"
)

print(
    f"Spearman rho     = {rho:.6f}"
)

print(
    "\nOutputs:"
)

for path in [
    OUT_PNG,
    OUT_PDF,
    OUT_TIFF,
]:

    print(path)
